//! 智能生成器 - 真正学习页面结构和内容，重新组织生成

use crate::common::StyleSystem;
use crate::generator::{GeneratedWebsite, WebsiteMetadata};
use crate::js_understander::FunctionIntents;
use crate::style_transform::TransformType;
use std::collections::HashMap;

/// 页面结构分析
#[derive(Debug, Clone)]
pub struct PageStructure {
    /// 页面标题
    pub title: String,
    /// 描述
    pub description: String,
    /// 主要区块
    pub sections: Vec<PageSection>,
    /// 导航项
    pub nav_items: Vec<NavItem>,
    /// 表单
    pub forms: Vec<FormInfo>,
    /// 按钮
    pub buttons: Vec<ButtonInfo>,
}

#[derive(Debug, Clone)]
pub struct PageSection {
    pub section_type: SectionType,
    pub heading: String,
    pub content: String,
    pub cta_text: Option<String>,
    pub cta_link: Option<String>,
}

#[derive(Debug, Clone)]
pub enum SectionType {
    Hero,
    Features,
    HowItWorks,
    Testimonials,
    CTA,
    Pricing,
    FAQ,
    Contact,
}

#[derive(Debug, Clone)]
pub struct NavItem {
    pub label: String,
    pub href: String,
}

#[derive(Debug, Clone)]
pub struct FormInfo {
    pub action: String,
    pub method: String,
    pub fields: Vec<FormField>,
    pub submit_text: String,
}

#[derive(Debug, Clone)]
pub struct FormField {
    pub field_type: String,
    pub name: String,
    pub placeholder: String,
    pub required: bool,
}

#[derive(Debug, Clone)]
pub struct ButtonInfo {
    pub text: String,
    pub action: String,
    pub style: String,
}

/// 智能网站生成器
pub struct SmartGenerator {
    structure: PageStructure,
    styles: StyleSystem,
    _intents: FunctionIntents,
}

/// 生成的网站（转换为标准格式）
pub type SmartGeneratedWebsite = GeneratedWebsite;

impl SmartGenerator {
    pub fn new(html: &str, styles: StyleSystem, intents: FunctionIntents) -> Self {
        let structure = Self::analyze_structure(html);
        Self {
            structure,
            styles,
            _intents: intents,
        }
    }

    /// 分析页面结构
    fn analyze_structure(html: &str) -> PageStructure {
        // 提取标题
        let title = Self::extract_title(html).unwrap_or_else(|| "Generated Website".to_string());

        // 提取描述
        let description = Self::extract_description(html)
            .unwrap_or_else(|| "A website generated by AI".to_string());

        // 提取导航
        let nav_items = Self::extract_nav_items(html);

        // 提取主要区块
        let sections = Self::extract_sections(html);

        // 提取表单
        let forms = Self::extract_forms(html);

        // 提取按钮
        let buttons = Self::extract_buttons(html);

        PageStructure {
            title,
            description,
            sections,
            nav_items,
            forms,
            buttons,
        }
    }

    fn extract_title(html: &str) -> Option<String> {
        // 提取<title>标签内容
        if let Some(start) = html.find("<title>") {
            if let Some(end) = html[start..].find("</title>") {
                let title = &html[start + 7..start + end];
                // 清理标题，只取主要部分
                let title = title.split("·").next().unwrap_or(title).trim();
                return Some(title.to_string());
            }
        }
        None
    }

    fn extract_description(html: &str) -> Option<String> {
        // 提取meta description
        if let Some(start) = html.find("name=\"description\"") {
            if let Some(content_start) = html[start..].find("content=\"") {
                let content_start = start + content_start + 9;
                if let Some(content_end) = html[content_start..].find("\"") {
                    return Some(html[content_start..content_start + content_end].to_string());
                }
            }
        }
        None
    }

    fn extract_nav_items(html: &str) -> Vec<NavItem> {
        let mut items = Vec::new();

        // 简单的导航链接提取
        let nav_patterns = [
            ("Product", "#product"),
            ("Features", "#features"),
            ("Pricing", "#pricing"),
            ("Contact", "#contact"),
        ];

        for (label, href) in nav_patterns.iter() {
            if html.to_lowercase().contains(&label.to_lowercase()) {
                items.push(NavItem {
                    label: label.to_string(),
                    href: href.to_string(),
                });
            }
        }

        if items.is_empty() {
            items.push(NavItem {
                label: "Home".to_string(),
                href: "/".to_string(),
            });
            items.push(NavItem {
                label: "About".to_string(),
                href: "#about".to_string(),
            });
        }

        items
    }

    fn extract_sections(html: &str) -> Vec<PageSection> {
        let mut sections = Vec::new();

        // 检测Hero区域
        if html.contains("hero") || html.contains("Hero") {
            sections.push(PageSection {
                section_type: SectionType::Hero,
                heading: Self::extract_hero_heading(html).unwrap_or_else(|| "Welcome".to_string()),
                content: Self::extract_hero_content(html)
                    .unwrap_or_else(|| "Discover our platform".to_string()),
                cta_text: Some("Get Started".to_string()),
                cta_link: Some("#signup".to_string()),
            });
        }

        // 检测Features区域
        if html.contains("feature") || html.contains("Feature") {
            sections.push(PageSection {
                section_type: SectionType::Features,
                heading: "Features".to_string(),
                content: "Explore what we offer".to_string(),
                cta_text: None,
                cta_link: None,
            });
        }

        // 检测CTA区域
        if html.contains("cta") || html.contains("CTA") || html.contains("sign up") {
            sections.push(PageSection {
                section_type: SectionType::CTA,
                heading: "Ready to start?".to_string(),
                content: "Join us today".to_string(),
                cta_text: Some("Sign Up Now".to_string()),
                cta_link: Some("/signup".to_string()),
            });
        }

        // 如果没有检测到任何区块，添加默认的
        if sections.is_empty() {
            sections.push(PageSection {
                section_type: SectionType::Hero,
                heading: "Welcome".to_string(),
                content: "Explore our platform".to_string(),
                cta_text: Some("Get Started".to_string()),
                cta_link: Some("#".to_string()),
            });
        }

        sections
    }

    fn extract_hero_heading(html: &str) -> Option<String> {
        // 尝试提取h1或hero区域的标题
        if let Some(start) = html.find("<h1") {
            if let Some(tag_end) = html[start..].find(">") {
                let content_start = start + tag_end + 1;
                if let Some(end) = html[content_start..].find("</h1>") {
                    let heading = html[content_start..content_start + end]
                        .replace("<br>", " ")
                        .replace("<br/>", " ");
                    return Some(heading.trim().to_string());
                }
            }
        }
        None
    }

    fn extract_hero_content(html: &str) -> Option<String> {
        // 尝试提取hero区域的描述
        if let Some(start) = html.find("<p") {
            if let Some(tag_end) = html[start..].find(">") {
                let content_start = start + tag_end + 1;
                if let Some(end) = html[content_start..].find("</p>") {
                    let content = html[content_start..content_start + end]
                        .replace("<br>", " ")
                        .replace("<br/>", " ");
                    if content.len() > 10 && content.len() < 200 {
                        return Some(content.trim().to_string());
                    }
                }
            }
        }
        None
    }

    fn extract_forms(html: &str) -> Vec<FormInfo> {
        let mut forms = Vec::new();

        // 检测是否有注册/登录表单
        if html.contains("signup") || html.contains("sign up") || html.contains("email") {
            forms.push(FormInfo {
                action: "/signup".to_string(),
                method: "POST".to_string(),
                fields: vec![FormField {
                    field_type: "email".to_string(),
                    name: "email".to_string(),
                    placeholder: "Enter your email".to_string(),
                    required: true,
                }],
                submit_text: "Sign Up".to_string(),
            });
        }

        forms
    }

    fn extract_buttons(html: &str) -> Vec<ButtonInfo> {
        let mut buttons = Vec::new();

        // 检测常见的CTA按钮
        if html.contains("sign up") || html.contains("signup") {
            buttons.push(ButtonInfo {
                text: "Sign Up".to_string(),
                action: "navigate:/signup".to_string(),
                style: "primary".to_string(),
            });
        }

        if html.contains("sign in") || html.contains("login") {
            buttons.push(ButtonInfo {
                text: "Sign In".to_string(),
                action: "navigate:/login".to_string(),
                style: "secondary".to_string(),
            });
        }

        buttons
    }

    /// 生成网站
    pub fn generate(&self, _theme: TransformType) -> SmartGeneratedWebsite {
        let html = self.generate_html();
        let css = self.generate_css();
        let js = self.generate_js();

        SmartGeneratedWebsite {
            html,
            css,
            js,
            component_tree: crate::generator::ComponentTree {
                root: crate::generator::ComponentNode {
                    id: "root".to_string(),
                    component_type: "div".to_string(),
                    children: vec![],
                    props: HashMap::new(),
                    classes: vec!["smart-generated".to_string()],
                },
                components: vec![],
            },
            metadata: WebsiteMetadata {
                title: self.structure.title.clone(),
                description: self.structure.description.clone(),
                components_used: vec![
                    "Header".to_string(),
                    "Nav".to_string(),
                    "Hero".to_string(),
                    "Footer".to_string(),
                ],
                features_implemented: vec![
                    "Form Validation".to_string(),
                    "Smooth Scroll".to_string(),
                ],
            },
        }
    }

    fn generate_html(&self) -> String {
        let mut html = String::new();

        // DOCTYPE和html标签
        html.push_str("<!DOCTYPE html>\n");
        html.push_str("<html lang=\"en\">\n");

        // Head
        html.push_str("<head>\n");
        html.push_str("<meta charset=\"UTF-8\">\n");
        html.push_str(
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n",
        );
        html.push_str(&format!("<title>{}</title>\n", self.structure.title));
        html.push_str(&format!(
            "<meta name=\"description\" content=\"{}\">\n",
            self.structure.description
        ));
        html.push_str("<link rel=\"stylesheet\" href=\"styles.css\">\n");
        html.push_str("</head>\n");

        // Body
        html.push_str("<body>\n");

        // Header/Nav
        html.push_str(&self.generate_nav());

        // Main content
        html.push_str("<main>\n");
        for section in &self.structure.sections {
            html.push_str(&self.generate_section(section));
        }
        html.push_str("</main>\n");

        // Footer
        html.push_str(&self.generate_footer());

        // Scripts
        html.push_str("<script src=\"script.js\"></script>\n");
        html.push_str("</body>\n");
        html.push_str("</html>");

        html
    }

    fn generate_nav(&self) -> String {
        let mut nav = String::new();

        nav.push_str("<header class=\"site-header\">\n");
        nav.push_str("  <nav class=\"main-nav\">\n");
        nav.push_str("    <a href=\"/\" class=\"logo\">");
        nav.push_str(&self.structure.title);
        nav.push_str("</a>\n");
        nav.push_str("    <ul class=\"nav-links\">\n");

        for item in &self.structure.nav_items {
            nav.push_str(&format!(
                "      <li><a href=\"{}\">{}</a></li>\n",
                item.href, item.label
            ));
        }

        nav.push_str("    </ul>\n");

        // 添加按钮
        for button in &self.structure.buttons {
            nav.push_str(&format!(
                "    <a href=\"{}\" class=\"btn btn-{}\">{}</a>\n",
                button.action.replace("navigate:", ""),
                button.style,
                button.text
            ));
        }

        nav.push_str("  </nav>\n");
        nav.push_str("</header>\n");

        nav
    }

    fn generate_section(&self, section: &PageSection) -> String {
        let mut html = String::new();

        let class_name = match section.section_type {
            SectionType::Hero => "hero-section",
            SectionType::Features => "features-section",
            SectionType::HowItWorks => "how-it-works",
            SectionType::Testimonials => "testimonials",
            SectionType::CTA => "cta-section",
            SectionType::Pricing => "pricing-section",
            SectionType::FAQ => "faq-section",
            SectionType::Contact => "contact-section",
        };

        html.push_str(&format!("<section class=\"{}\">\n", class_name));
        html.push_str("  <div class=\"container\">\n");
        html.push_str(&format!("    <h2>{}</h2>\n", section.heading));
        html.push_str(&format!("    <p>{}</p>\n", section.content));

        // CTA按钮
        if let (Some(text), Some(link)) = (&section.cta_text, &section.cta_link) {
            html.push_str(&format!(
                "    <a href=\"{}\" class=\"btn btn-primary\">{}</a>\n",
                link, text
            ));
        }

        // 表单
        for form in &self.structure.forms {
            html.push_str(&self.generate_form(form));
        }

        html.push_str("  </div>\n");
        html.push_str("</section>\n");

        html
    }

    fn generate_form(&self, form: &FormInfo) -> String {
        let mut html = String::new();

        html.push_str(&format!(
            "<form action=\"{}\" method=\"{}\" class=\"signup-form\">\n",
            form.action, form.method
        ));

        for field in &form.fields {
            html.push_str(&format!(
                "<input type=\"{}\" name=\"{}\" placeholder=\"{}\" {}>\n",
                field.field_type,
                field.name,
                field.placeholder,
                if field.required { "required" } else { "" }
            ));
        }

        html.push_str(&format!(
            "<button type=\"submit\" class=\"btn btn-primary\">{}</button>\n",
            form.submit_text
        ));

        html.push_str("</form>\n");

        html
    }

    fn generate_footer(&self) -> String {
        let mut footer = String::new();

        footer.push_str("<footer class=\"site-footer\">\n");
        footer.push_str("  <div class=\"container\">\n");
        footer.push_str(&format!(
            "    <p>&copy; 2024 {}. All rights reserved.</p>\n",
            self.structure.title
        ));
        footer.push_str("  </div>\n");
        footer.push_str("</footer>\n");

        footer
    }

    fn generate_css(&self) -> String {
        let mut css = String::new();

        // CSS变量
        css.push_str(":root {\n");

        // 提取颜色
        for (i, color) in self
            .styles
            .colors
            .primary_colors
            .iter()
            .take(10)
            .enumerate()
        {
            css.push_str(&format!("  --color-primary-{}: {};\n", i, color.hex));
        }

        // 主题色
        let primary = self
            .styles
            .colors
            .primary_colors
            .first()
            .map(|c| c.hex.clone())
            .unwrap_or_else(|| "#3498db".to_string());

        css.push_str(&format!("  --primary: {};\n", primary));
        css.push_str("  --secondary: #2ecc71;\n");
        css.push_str("  --text: #333;\n");
        css.push_str("  --bg: #fff;\n");
        css.push_str("  --font-main: system-ui, -apple-system, sans-serif;\n");
        css.push_str("}\n\n");

        // 基础样式
        css.push_str("* { margin: 0; padding: 0; box-sizing: border-box; }\n\n");
        css.push_str(
            "body { font-family: var(--font-main); line-height: 1.6; color: var(--text); }\n\n",
        );
        css.push_str(".container { max-width: 1200px; margin: 0 auto; padding: 0 20px; }\n\n");

        // Header
        css.push_str(".site-header { background: var(--bg); border-bottom: 1px solid #eee; padding: 1rem 0; }\n");
        css.push_str(".main-nav { display: flex; justify-content: space-between; align-items: center; max-width: 1200px; margin: 0 auto; padding: 0 20px; }\n");
        css.push_str(".logo { font-size: 1.5rem; font-weight: bold; color: var(--primary); text-decoration: none; }\n");
        css.push_str(".nav-links { display: flex; list-style: none; gap: 2rem; }\n");
        css.push_str(".nav-links a { text-decoration: none; color: var(--text); }\n\n");

        // Hero
        css.push_str(".hero-section { padding: 5rem 0; text-align: center; background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%); color: white; }\n");
        css.push_str(".hero-section h2 { font-size: 3rem; margin-bottom: 1rem; }\n");
        css.push_str(
            ".hero-section p { font-size: 1.25rem; margin-bottom: 2rem; opacity: 0.9; }\n\n",
        );

        // Buttons
        css.push_str(".btn { display: inline-block; padding: 0.75rem 1.5rem; border-radius: 6px; text-decoration: none; font-weight: 500; transition: all 0.2s; }\n");
        css.push_str(".btn-primary { background: var(--primary); color: white; }\n");
        css.push_str(".btn-primary:hover { opacity: 0.9; transform: translateY(-2px); }\n");
        css.push_str(".btn-secondary { background: transparent; color: var(--primary); border: 2px solid var(--primary); }\n\n");

        // Forms
        css.push_str(".signup-form { display: flex; gap: 1rem; justify-content: center; margin-top: 2rem; }\n");
        css.push_str(".signup-form input { padding: 0.75rem 1rem; border: 1px solid #ddd; border-radius: 6px; min-width: 300px; }\n\n");

        // Sections
        css.push_str(".features-section { padding: 4rem 0; }\n");
        css.push_str(
            ".cta-section { padding: 4rem 0; background: #f8f9fa; text-align: center; }\n\n",
        );

        // Footer
        css.push_str(".site-footer { background: #2c3e50; color: white; padding: 2rem 0; text-align: center; }\n");

        css
    }

    fn generate_js(&self) -> String {
        let mut js = String::new();

        js.push_str("// Generated JavaScript\n");
        js.push_str("document.addEventListener('DOMContentLoaded', function() {\n");
        js.push_str("  console.log('Website loaded');\n");
        js.push_str("  \n");
        js.push_str("  // Form validation\n");
        js.push_str("  document.querySelectorAll('form').forEach(form => {\n");
        js.push_str("    form.addEventListener('submit', function(e) {\n");
        js.push_str("      const email = form.querySelector('input[type=\"email\"]');\n");
        js.push_str("      if (email && !email.value.includes('@')) {\n");
        js.push_str("        e.preventDefault();\n");
        js.push_str("        alert('Please enter a valid email');\n");
        js.push_str("      }\n");
        js.push_str("    });\n");
        js.push_str("  });\n");
        js.push_str("  \n");
        js.push_str("  // Smooth scroll\n");
        js.push_str("  document.querySelectorAll('a[href^=\"#\"]').forEach(anchor => {\n");
        js.push_str("    anchor.addEventListener('click', function(e) {\n");
        js.push_str("      e.preventDefault();\n");
        js.push_str("      const target = document.querySelector(this.getAttribute('href'));\n");
        js.push_str("      if (target) target.scrollIntoView({ behavior: 'smooth' });\n");
        js.push_str("    });\n");
        js.push_str("  });\n");
        js.push_str("});\n");

        js
    }
}
