//! HTML Generator
//!
//! Generates HTML code based on website intent and features.

use crate::learning_sandbox::intent_analyzer::WebsiteIntent;
use anyhow::Result;
use chrono::Datelike;

/// HTML Generator Configuration
#[derive(Debug, Clone)]
pub struct HtmlGeneratorConfig {
    /// Use semantic HTML5 elements
    pub semantic_html: bool,

    /// Include ARIA attributes
    pub include_aria: bool,

    /// Generate responsive images
    pub responsive_images: bool,
}

impl Default for HtmlGeneratorConfig {
    fn default() -> Self {
        Self {
            semantic_html: true,
            include_aria: true,
            responsive_images: true,
        }
    }
}

/// HTML Generator
///
/// Generates HTML code based on website intent.
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct HtmlGenerator {
    config: HtmlGeneratorConfig,
}

impl HtmlGenerator {
    /// Create a new HTML generator
    pub fn new() -> Self {
        Self::with_config(HtmlGeneratorConfig::default())
    }

    /// Create with custom configuration
    pub fn with_config(config: HtmlGeneratorConfig) -> Self {
        Self { config }
    }

    /// Generate HTML based on intent
    pub async fn generate(&self, intent: &WebsiteIntent) -> Result<String> {
        let mut html = String::new();

        // DOCTYPE
        html.push_str("<!DOCTYPE html>\n");

        // HTML tag with language
        html.push_str("<html lang=\"en\">\n");

        // Head section
        html.push_str("<head>\n");
        html.push_str("    <meta charset=\"UTF-8\">\n");

        // Viewport
        html.push_str(
            "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n",
        );

        // Title
        let title = self.generate_title(intent);
        html.push_str(&format!("    <title>{}</title>\n", title));

        // Meta description
        if let Some(desc) = self.generate_description(intent) {
            html.push_str(&format!(
                "    <meta name=\"description\" content=\"{}\">\n",
                desc
            ));
        }

        // CSS link
        html.push_str("    <link rel=\"stylesheet\" href=\"css/main.css\">\n");

        html.push_str("</head>\n");

        // Body section
        html.push_str("<body>\n");

        // Header
        if intent.structure.has_header {
            html.push_str(&self.generate_header(intent));
        }

        // Navigation
        if intent.structure.has_navigation {
            html.push_str(&self.generate_navigation(intent));
        }

        // Main content
        html.push_str("<main class=\"main-content\">\n");
        html.push_str(&self.generate_main_content(intent));
        html.push_str("</main>\n");

        // Sidebar
        if intent.structure.has_sidebar {
            html.push_str("<aside class=\"sidebar\">\n");
            html.push_str("    <!-- Sidebar content -->\n");
            html.push_str("</aside>\n");
        }

        // Footer
        if intent.structure.has_footer {
            html.push_str(&self.generate_footer(intent));
        }

        // Scripts
        html.push_str("<script src=\"js/main.js\"></script>\n");

        html.push_str("</body>\n");
        html.push_str("</html>");

        Ok(html)
    }

    fn generate_title(&self, intent: &WebsiteIntent) -> String {
        format!("{} - Generated by BrowerAI", intent.website_type)
    }

    fn generate_description(&self, intent: &WebsiteIntent) -> Option<String> {
        if intent.core_features.is_empty() {
            return None;
        }

        let features = intent.core_features.join(", ");
        Some(format!(
            "A {} website with features: {}",
            intent.website_type, features
        ))
    }

    fn generate_header(&self, intent: &WebsiteIntent) -> String {
        format!(
            r#"    <header class="header">
        <div class="container">
            <div class="logo">
                <h1>{}</h1>
            </div>
        </div>
    </header>
"#,
            intent.website_type.replace("-", " ").to_uppercase()
        )
    }

    fn generate_navigation(&self, intent: &WebsiteIntent) -> String {
        let mut nav_items = vec![
            "Home".to_string(),
            "About".to_string(),
            "Services".to_string(),
            "Contact".to_string(),
        ];

        // Add feature-specific items
        if intent.core_features.iter().any(|f| f.contains("account")) {
            nav_items.push("My Account".to_string());
        }
        if intent
            .core_features
            .iter()
            .any(|f| f.contains("cart") || f.contains("checkout"))
        {
            nav_items.push("Cart".to_string());
        }

        let items_html: Vec<String> = nav_items
            .iter()
            .map(|item| {
                format!(
                    "                <li><a href=\"#\">{placeholder}</a></li>",
                    placeholder = item
                )
            })
            .collect();

        format!(
            r#"    <nav class="navigation">
        <div class="container">
            <ul class="nav-list">
{}
            </ul>
        </div>
    </nav>
"#,
            items_html.join("\n")
        )
    }

    fn generate_main_content(&self, intent: &WebsiteIntent) -> String {
        let mut content = String::new();

        // Hero section
        content.push_str("        <section class=\"hero\">\n");
        content.push_str(&format!(
            "            <h2>Welcome to our {}</h2>\n",
            intent.website_type.replace("-", " ")
        ));
        content.push_str("            <p>Explore our features and services.</p>\n");
        content.push_str("        </section>\n\n");

        // Features section based on detected features
        if !intent.core_features.is_empty() {
            content.push_str("        <section class=\"features\">\n");
            content.push_str("            <h3>Our Features</h3>\n");
            content.push_str("            <div class=\"feature-grid\">\n");

            for feature in intent.core_features.iter().take(6) {
                let feature_name = feature.replace("_", " ");
                content.push_str("                <div class=\"feature-card\">\n");
                content.push_str(&format!(
                    "                    <h4>{}</h4>\n",
                    feature_name
                        .split_whitespace()
                        .map(
                            |w| w.chars().next().unwrap().to_uppercase().collect::<String>()
                                + &w[1..]
                        )
                        .collect::<Vec<_>>()
                        .join(" ")
                ));
                content.push_str(&format!(
                    "                    <p>Discover more about {} on our website.</p>\n",
                    feature_name
                ));
                content.push_str("                </div>\n");
            }

            content.push_str("            </div>\n");
            content.push_str("        </section>\n\n");
        }

        content
    }

    fn generate_footer(&self, intent: &WebsiteIntent) -> String {
        let current_year = chrono::Utc::now().year();

        format!(
            r#"    <footer class="footer">
        <div class="container">
            <p>&copy; {} {} - Generated by BrowerAI</p>
        </div>
    </footer>
"#,
            current_year,
            intent.website_type.replace("-", " ")
        )
    }
}

impl Default for HtmlGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::learning_sandbox::intent_analyzer::{
        ComplexityLevel, DesignStyle, LayoutType, PageStructure, WebsiteIntent,
    };
    use std::collections::HashMap;

    #[test]
    fn test_html_generator_creation() {
        let generator = HtmlGenerator::new();
        assert!(generator.config.semantic_html);
    }

    #[test]
    fn test_generate_ecommerce() {
        let generator = HtmlGenerator::new();

        let intent = WebsiteIntent {
            website_type: "e-commerce".to_string(),
            confidence: 0.9,
            core_features: vec!["shopping_cart".to_string(), "checkout".to_string()],
            target_audience: "consumers".to_string(),
            design_style: DesignStyle::default(),
            structure: PageStructure {
                has_header: true,
                has_navigation: true,
                has_sidebar: false,
                has_main_content: true,
                has_footer: true,
                layout_type: LayoutType::SingleColumn,
                section_count: 5,
                complexity: ComplexityLevel::Moderate,
            },
            business_model: "B2C".to_string(),
            type_scores: HashMap::new(),
        };

        let html = tokio::runtime::Runtime::new()
            .unwrap()
            .block_on(generator.generate(&intent))
            .unwrap();

        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("<header"));
        assert!(html.contains("<nav"));
        assert!(html.contains("<main"));
        assert!(html.contains("<footer"));
        assert!(html.contains("shopping_cart"));
    }

    #[test]
    fn test_generate_simple() {
        let generator = HtmlGenerator::new();

        let intent = WebsiteIntent {
            website_type: "blog".to_string(),
            confidence: 0.8,
            core_features: vec!["article_reader".to_string()],
            target_audience: "readers".to_string(),
            design_style: DesignStyle::default(),
            structure: PageStructure {
                has_header: true,
                has_navigation: true,
                has_sidebar: true,
                has_main_content: true,
                has_footer: true,
                layout_type: LayoutType::TwoColumn,
                section_count: 3,
                complexity: ComplexityLevel::Simple,
            },
            business_model: "content".to_string(),
            type_scores: HashMap::new(),
        };

        let html = tokio::runtime::Runtime::new()
            .unwrap()
            .block_on(generator.generate(&intent))
            .unwrap();

        assert!(html.contains("E-COMMERCE") || html.contains("BLOG"));
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("main.css"));
    }
}
